# Generated by Django 3.2.9 on 2021-11-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('one way', 'one way'), ('return', 'return')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='trip',
            field=models.CharField(choices=[('up country', 'up country'), ('town service', 'town service')], max_length=100),
        ),
    ]
