# Generated by Django 3.2.9 on 2021-11-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
    ]
