# Generated by Django 3.2.9 on 2021-11-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticketing',
            new_name='Ticket',
        ),
    ]
