# Generated by Django 3.2.9 on 2021-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='infants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
