# Generated by Django 3.2.9 on 2021-11-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211125_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default=1, upload_to='package'),
            preserve_default=False,
        ),
    ]
