# Generated by Django 3.2.9 on 2021-11-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211129_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
