# Generated by Django 3.2.9 on 2021-11-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211128_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='carhire',
            name='driven_by',
            field=models.CharField(choices=[('driver', 'driver'), ('self', 'self')], default='driver', max_length=40),
        ),
    ]
