# Generated by Django 3.2.9 on 2021-11-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_ticketing_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomadation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.CharField(choices=[('budget', 'budget'), ('mid range', 'mid range'), ('up market', 'up market')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100)),
                ('driver', models.CharField(choices=[('driver', 'driver'), ('self', 'self')], max_length=100)),
                ('budget', models.CharField(choices=[('Up Country', 'Up Country'), ('Town Service', 'Town Service')], max_length=100)),
                ('pickup', models.CharField(max_length=100)),
                ('dropoff', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.packagecategory')),
            ],
        ),
    ]
