# Generated by Django 3.2.9 on 2021-11-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_car_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car',
            new_name='capacity',
        ),
    ]
