# Generated by Django 3.2.9 on 2021-11-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211124_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('group', 'group'), ('custom', 'custom')], max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('slots', models.PositiveIntegerField(default=0)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('activities', models.CharField(choices=[('group', 'group'), ('custom', 'custom')], max_length=200)),
                ('pickup', models.CharField(max_length=100)),
                ('dropoff', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('arrival_accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_accom', to='myapp.accomadation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.packagecategory')),
                ('trip_accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_accom', to='myapp.accomadation')),
            ],
        ),
    ]
