# Generated by Django 3.2.9 on 2021-11-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_carhire_driven_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carhire',
            name='trip',
            field=models.CharField(choices=[('up country', 'up country'), ('town service', 'town service')], default='up country', max_length=100),
        ),
    ]
