# Generated by Django 3.2.9 on 2021-11-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(default=1, upload_to='flights'),
            preserve_default=False,
        ),
    ]
