# Generated by Django 3.2.9 on 2021-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='transport',
            name='trip',
            field=models.CharField(choices=[('Up Country', 'Up Country'), ('Town Service', 'Town Service')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='budget',
            field=models.CharField(choices=[('budget', 'budget'), ('mid range', 'mid range'), ('up market', 'up market')], max_length=100),
        ),
    ]
