# Generated by Django 3.2.9 on 2021-11-29 20:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211129_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='nationality',
        ),
        migrations.AddField(
            model_name='booking',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
