# Generated by Django 3.2.9 on 2021-11-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211127_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
