# Generated by Django 3.2.9 on 2021-11-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211129_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
    ]
