# Generated by Django 3.2.9 on 2021-11-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_car_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomadation',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
