# Generated by Django 3.2.9 on 2021-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_partners_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('gallery', 'gallery'), ('partner', 'partner')], default='gallery', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
