# Generated by Django 3.2.9 on 2021-11-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211127_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='dropoff',
        ),
        migrations.RemoveField(
            model_name='package',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='package',
            name='telephone',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('pickup', models.CharField(max_length=100)),
                ('dropoff', models.CharField(max_length=100)),
                ('slots', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
            ],
        ),
    ]
