# Generated by Django 3.2.9 on 2021-11-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211130_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='hide',
            new_name='hidden',
        ),
    ]
