# Generated by Django 3.2.9 on 2021-11-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211130_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='permit_class',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
